using Hellclient.World.States;
using Hellclient.World.Types;
using Hellclient.World.Types;
using Timer = Hellclient.World.Types.Timer;

namespace Hellclient.World.Cores;

public interface IWorld
{
    public string ID { get; }
    public WorldEventBus EventBus { get; }
    public int GetMaxHistory();
    public int GetMaxLines();
    public int GetMaxRecent();
	public byte[] GetConnBuffer();
	public bool GetConnConnected();
	public string GetHost();
	public void SetHost(string host);
	public string GetPort();
	public void SetPort(string port);
	public string GetProxy();
	public void SetProxy(string proxy);
	public string GetName();
	public void SetName(string name);
	public bool GetShowBroadcast();
	public void SetShowBroadcast(bool showBroadcast);
	public bool GetShowSubneg();
	public void SetShowSubneg(bool showSubneg);
	public bool GetModEnabled();
	public void SetModEnabled(bool modEnabled);
	public bool GetAutoSave();
	public void SetAutoSave(bool autoSave);
	public bool GetIgnoreBatchCommand();
	public void SetIgnoreBatchCommand(bool ignoreBatchCommand);
	public string GetCommandStackCharacter();
	public void SetCommandStackCharacter(string commandStackCharacter);
	public string GetScriptPrefix();
	public void SetScriptPrefix(string scriptPrefix);

    public string GetStatus();
    public void SetStatus(string status);
    public int GetQueueDelay();
    public void SetQueueDelay(int queueDelay);
    public List<Command> GetQueue();
    public string GetParam(string key);
    public Dictionary<string, string> GetParams();
    public void SetParam(string key, string value);
    public void DeleteParam(string key);
    public string GetParamComment(string key);
    public Dictionary<string, string> GetParamComments();
    public void SetParamComment(string key, string comment);
    public string GetCharset();
    public void SetCharset(string charset);
    public long GetReadyAt();
    public int GetPosition();
    public void SetPosition(int position);
    public List<Line> GetCurrentLines();
    public Line? GetPrompt();
    public ClientInfo? GetClientInfo();
    public WorldData? GetWorldData();
    public ScriptData? GetScriptData();
    public void SetPermissions(string[] permissions);
    public string[] GetPermissions();
    public void RequestPermissions(Authorization authorization);
    public string GetScriptID();
    public void SetScriptID(string scriptID);
    public string GetScriptType();
    public string GetScriptPath();
    public string GetModPath();
    public string GetCorePath();
    public string GetScriptModPath();
    public string GetLogsPath();
    public string GetScriptHome();
    public void DoLog(string message);
    public void SetTrusted(Trusted trusted);
    public Trusted? GetTrusted();
    public void RequestTrustDomains(Authorization authorization);
    public object GetPluginOptions();
    public void DoReloadPermissions();
    public void DoSendToConn(byte[] cmd);
    public void DoSend(Command command);
    public void DoSendToQueue(Command command);
    public void DoExecute(string message);
    public (byte[] Data, Exception? Error) DoEncode();
    public Exception? DoDecode(byte[] data);
    public Exception? DoReloadScript();
    public Exception? DoSaveScript();
    public void DoUseScript(string scriptPath);
    public List<RequiredParam> GetRequiredParams();
    public void DoRunScript(string script);
    public void DoPrint(string msg);
    public void DoPrintSystem(string msg);
    public void DoPrintLocalBroadcastIn(string msg);
    public void DoPrintGlobalBroadcastIn(string msg);
    public void DoPrintLocalBroadcastOut(string msg);
    public void DoPrintGlobalBroadcastOut(string msg);
    public void DoPrintSubneg(string msg);
    public void DoPrintRequest(string msg);
    public void DoPrintResponse(string msg);

    public int DoDiscardQueue(bool force);
    public void DoLockQueue();
    public void DoOmitOutput();
    public void DoDeleteLines(int count);
    public int GetLineCount();
    public void DoSendHUDClickToScript(Click click);
    public void DoSendBroadcastToScript(Broadcast broadcast);
    public bool HandleBuffer(byte[] buffer);
    public bool HandleSubneg(byte[] buffer);
    public void HandleFocus();
    public void HandleLoseFocus();
    public void DoSendTimerToScript(Timer timer);
    public bool DoDeleteTimer(string id);
    public bool DoDeleteTimerByName(string name);
    public int DoDeleteTemporaryTimers();
    public int DoDeleteTimerGroup(string group, bool byUser);
    public bool DoEnableTimerByName(string name, bool enabled);
    public int DoEnableTimerGroup(string group, bool enabled);
    public bool DoResetNamedTimer(string name);
    public Timer? GetTimer(string name);
    public List<Timer> GetTimersByType(bool byUser);
    public void DoDeleteTimerByType(bool byUser);
    public void AddTimers(List<Timer> ts);
    public void DoResetTimers();
    public (string Value, bool Found, bool Valid) GetTimerOption(string name, string option);
    public (string Value, bool Found, bool Valid) GetTimerInfo(string name, int infotype);
    public (bool Updated, bool Found, bool Valid) SetTimerOption(string name, string option, string value);
    public bool HasNamedTimer(string name);
    public string[] DoListTimerNames(bool byUser);
    public bool AddTimer(Timer timer, bool byUser);
    public int DoUpdateTimer(Timer timer);
    public void DoSendAliasToScript(string message, Alias alias, Matcher result);

    public bool DoDeleteAlias(string id);
    public bool DoDeleteAliasByName(string name);
    public int DoDeleteTemporaryAliases();
    public int DoDeleteAliasGroup(string group, bool byUser);
    public bool DoEnableAliasByName(string name, bool enabled);
    public int DoEnableAliasGroup(string group, bool enabled);
    public Alias? GetAlias(string name);
    public List<Alias> GetAliasesByType(bool byUser);
    public void DoDeleteAliasByType(bool byUser);
    public void AddAliases(List<Alias> aliases);
    public (string Value, bool Found, bool Valid) GetAliasOption(string name, string option);
    public (string Value, bool Found, bool Valid) GetAliasInfo(string name, int infotype);
    public (bool Updated, bool Found, bool Valid) SetAliasOption(string name, string option, string value);
    public bool HasNamedAlias(string name);
    public string[] DoListAliasNames(bool byUser);
    public bool AddAlias(Alias alias, bool byUser);
    public int DoUpdateAlias(Alias alias);

    public bool DoDeleteTrigger(string id);
    public bool DoDeleteTriggerByName(string name);
    public int DoDeleteTemporaryTriggers();
    public int DoDeleteTriggerGroup(string group, bool byUser);
    public bool DoEnableTriggerByName(string name, bool enabled);
    public int DoEnableTriggerGroup(string group, bool enabled);
    public Trigger? GetTrigger(string name);
    public List<Trigger> GetTriggersByType(bool byUser);
    public void DoDeleteTriggerByType(bool byUser);
    public void AddTriggers(List<Trigger> triggers);
    public (string Value, bool Found, bool Valid) GetTriggerOption(string name, string option);
    public (string Value, bool Found, bool Valid) GetTriggerInfo(string name, int infotype);
    public (bool Updated, bool Found, bool Valid) SetTriggerOption(string name, string option, string value);
    public bool HasNamedTrigger(string name);
    public string[] DoListTriggerNames(bool byUser);
    public bool AddTrigger(Trigger trigger, bool byUser);
    public int DoUpdateTrigger(Trigger trigger);
    public void DoSendTriggerToScript(Line line, Trigger trigger, Matcher result);
    public Matcher? DoGetTriggerWildcard(string name);
    public void DoSendCallbackToScript(Callback cb);
    public void DoSendKeyUpToScript(string key);
    public void DoAssist();
    public void DoMultiLinesAppend(string line);
    public void DoMultiLinesFlush();
    public string[] DoMultiLinesLast(int count);
    public int GetLinesInBufferCount();
    public List<Line> GetRecentLines(int count);
    public Line? GetLine(int idx);
    public IMapper? GetMapper();
    public int GetPriority();
    public void SetPriority(int priority);
    public List<Line> GetSummary();
    public void SetSummary(List<Line> lines);
    public void UpdateLastActive();
    public long GetLastActive();
    public void AddHistory(string value);
    public string[] GetHistories();
    public void FlushHistories();
    public void HandleConnReceive(byte[] msg);
    public void HandleConnError(Exception err);
    public void HandleConnPrompt(byte[] msg);
    public void DoConnectServer();
    public void DoCloseServer();
    public void HandleConverterError(Exception err);
    public void HandleCmdError(Exception err);
    public void HandleTriggerError(Exception err);
    public void HandleScriptError(Exception err);
    public (string, string) GetScriptCaller();
    public void DoStopEvaluatingTriggers();

    public int GetMetronomeBeats();
    public void SetMetronomeBeats(int beats);
    public void DoResetMetronome();
    public int GetMetronomeSpace();
    public string[] GetMetronomeQueue();
    public bool DoDiscardMetronome(bool force);
    public void DoLockMetronomeQueue();
    public void DoFullMetronome();
    public void DoFullTickMetronome();
    public void SetMetronomeInterval(TimeSpan interval);
    public TimeSpan GetMetronomeInterval();
    public void SetMetronomeTick(TimeSpan tick);
    public TimeSpan GetMetronomeTick();
    public void DoPushMetronome(List<Command> cmds, bool grouped);
    public void DoMetronomeSend(Command cmds);
    public void DoMetronomeLock();
    public void DoSendResponseToScript(Message msg);

    public int GetHUDSize();
    public void SetHUDSize(int size);
    public List<Line> GetHUDContent();
    public bool UpdateHUDContent(int start, List<Line> content);

}
