using Microsoft.ClearScript.V8;
using Hellclient.V8Engine.Features.States;

namespace Hellclient.V8Engine.Features.Services;

public partial class V8ScriptService
{
    private void AppendToWorld(V8ScriptEngine engine, Dictionary<string, object> world, string name, object call)
    {
        engine.AddHostObject(name, call);
        world[name.ToLower()] = call;
        if (name.ToLower() != name)
        {
            world[name] = call;
        }
    }
    private void initJsAPI(V8EngineContext context)
    {
        var local = context.Runtime;
        var a = context.JsAPI;
        var world = new Dictionary<string, object>();
#pragma warning disable CS8974 // 将方法组转换为非委托类型
        AppendToWorld(local, world, "print", a.Print);
        AppendToWorld(local, world, "Note", a.Note);
        AppendToWorld(local, world, "SendImmediate", a.SendImmediate);
        AppendToWorld(local, world, "Send", a.Send);
        AppendToWorld(local, world, "SendNoEcho", a.SendNoEcho);
        AppendToWorld(local, world, "GetVariable", a.GetVariable);
        AppendToWorld(local, world, "SetVariable", a.SetVariable);
        AppendToWorld(local, world, "DeleteVariable", a.DeleteVariable);
        AppendToWorld(local, world, "GetVariableList", a.GetVariableList);
        AppendToWorld(local, world, "GetVariableComment", a.GetVariableComment);
        AppendToWorld(local, world, "SetVariableComment", a.SetVariableComment);
        AppendToWorld(local, world, "Version", a.Version);
        AppendToWorld(local, world, "Hash", a.Hash);
        AppendToWorld(local, world, "Base64Encode", a.Base64Encode);
        AppendToWorld(local, world, "Base64Decode", a.Base64Decode);
        AppendToWorld(local, world, "Connect", a.Connect);
        AppendToWorld(local, world, "IsConnected", a.IsConnected);
        AppendToWorld(local, world, "Disconnect", a.Disconnect);
        AppendToWorld(local, world, "GetWorldById", a.GetWorldById);
        AppendToWorld(local, world, "GetWorld", a.GetWorld);
        AppendToWorld(local, world, "GetWorldID", a.GetWorldID);
        AppendToWorld(local, world, "GetWorldIdList", a.GetWorldIdList);
        AppendToWorld(local, world, "GetWorldList", a.GetWorldList);
        AppendToWorld(local, world, "WorldName", a.WorldName);
        AppendToWorld(local, world, "WorldAddress", a.WorldAddress);
        AppendToWorld(local, world, "WorldPort", a.WorldPort);
        AppendToWorld(local, world, "WorldProxy", a.WorldProxy);
        AppendToWorld(local, world, "Trim", a.Trim);
        AppendToWorld(local, world, "GetUniqueNumber", a.GetUniqueNumber);
        AppendToWorld(local, world, "GetUniqueID", a.GetUniqueID);
        AppendToWorld(local, world, "CreateGUID", a.CreateGUID);
        AppendToWorld(local, world, "FlashIcon", a.FlashIcon);
        AppendToWorld(local, world, "SetStatus", a.SetStatus);
        AppendToWorld(local, world, "Execute", a.Execute);
        AppendToWorld(local, world, "DeleteCommandHistory", a.DeleteCommandHistory);
        AppendToWorld(local, world, "DiscardQueue", a.DiscardQueue);
        AppendToWorld(local, world, "LockQueue", a.LockQueue);
        AppendToWorld(local, world, "GetQueue", a.GetQueue);
        AppendToWorld(local, world, "Queue", a.Queue);
        AppendToWorld(local, world, "DoAfter", a.DoAfter);
        AppendToWorld(local, world, "DoAfterNote", a.DoAfterNote);
        AppendToWorld(local, world, "DoAfterSpeedWalk", a.DoAfterSpeedWalk);
        AppendToWorld(local, world, "DoAfterSpecial", a.DoAfterSpecial);
        AppendToWorld(local, world, "DeleteGroup", a.DeleteGroup);
        AppendToWorld(local, world, "AddTimer", a.AddTimer);
        AppendToWorld(local, world, "DeleteTimer", a.DeleteTimer);
        AppendToWorld(local, world, "DeleteTemporaryTimers", a.DeleteTemporaryTimers);
        AppendToWorld(local, world, "DeleteTimerGroup", a.DeleteTimerGroup);
        AppendToWorld(local, world, "EnableTimer", a.EnableTimer);
        AppendToWorld(local, world, "EnableTimerGroup", a.EnableTimerGroup);
        AppendToWorld(local, world, "GetTimerList", a.GetTimerList);
        AppendToWorld(local, world, "IsTimer", a.IsTimer);
        AppendToWorld(local, world, "ResetTimer", a.ResetTimer);
        AppendToWorld(local, world, "ResetTimers", a.ResetTimers);
        AppendToWorld(local, world, "GetTimerOption", a.GetTimerOption);
        AppendToWorld(local, world, "SetTimerOption", a.SetTimerOption);
        AppendToWorld(local, world, "AddAlias", a.AddAlias);
        AppendToWorld(local, world, "DeleteAlias", a.DeleteAlias);
        AppendToWorld(local, world, "DeleteTemporaryAliases", a.DeleteTemporaryAliases);
        AppendToWorld(local, world, "DeleteAliasGroup", a.DeleteAliasGroup);
        AppendToWorld(local, world, "EnableAlias", a.EnableAlias);
        AppendToWorld(local, world, "EnableAliasGroup", a.EnableAliasGroup);
        AppendToWorld(local, world, "GetAliasList", a.GetAliasList);
        AppendToWorld(local, world, "IsAlias", a.IsAlias);
        AppendToWorld(local, world, "GetAliasOption", a.GetAliasOption);
        AppendToWorld(local, world, "SetAliasOption", a.SetAliasOption);
        AppendToWorld(local, world, "AddTrigger", a.AddTrigger);
        AppendToWorld(local, world, "AddTriggerEx", a.AddTriggerEx);
        AppendToWorld(local, world, "DeleteTrigger", a.DeleteTrigger);
        AppendToWorld(local, world, "DeleteTemporaryTriggers", a.DeleteTemporaryTriggers);
        AppendToWorld(local, world, "DeleteTriggerGroup", a.DeleteTriggerGroup);
        AppendToWorld(local, world, "EnableTrigger", a.EnableTrigger);
        AppendToWorld(local, world, "EnableTriggerGroup", a.EnableTriggerGroup);
        AppendToWorld(local, world, "GetTriggerList", a.GetTriggerList);
        AppendToWorld(local, world, "IsTrigger", a.IsTrigger);
        AppendToWorld(local, world, "GetTriggerOption", a.GetTriggerOption);
        AppendToWorld(local, world, "SetTriggerOption", a.SetTriggerOption);
        AppendToWorld(local, world, "StopEvaluatingTriggers", a.StopEvaluatingTriggers);
        AppendToWorld(local, world, "GetTriggerWildcard", a.GetTriggerWildcard);
        AppendToWorld(local, world, "ColourNameToRGB", a.ColourNameToRGB);
        AppendToWorld(local, world, "SetSpeedWalkDelay", a.SetSpeedWalkDelay);
        AppendToWorld(local, world, "GetSpeedWalkDelay", a.GetSpeedWalkDelay);
        AppendToWorld(local, world, "HasFile", a.NewHasFileAPI);
        AppendToWorld(local, world, "ReadFile", a.NewReadFileAPI);
        AppendToWorld(local, world, "ReadLines", a.NewReadLinesAPI);
        AppendToWorld(local, world, "HasModFile", a.NewHasModFileAPI);
        AppendToWorld(local, world, "ReadModFile", a.NewReadModFileAPI);
        AppendToWorld(local, world, "ReadModLines", a.NewReadModLinesAPI);
        AppendToWorld(local, world, "GetModInfo", a.NewGetModInfoAPI);
        AppendToWorld(local, world, "MakeHomeFolder", a.NewMakeHomeFolderAPI);
        AppendToWorld(local, world, "HasHomeFile", a.NewHasHomeFileAPI);
        AppendToWorld(local, world, "ReadHomeFile", a.NewReadHomeFileAPI);
        AppendToWorld(local, world, "ReadHomeLines", a.NewReadHomeLinesAPI);
        AppendToWorld(local, world, "WriteHomeFile", a.NewWriteHomeFileAPI);
        AppendToWorld(local, world, "MakeSharedFolder", a.NewMakeSharedFolderAPI);
        AppendToWorld(local, world, "HasSharedFile", a.NewHasSharedFileAPI);
        AppendToWorld(local, world, "ReadSharedFile", a.NewReadSharedFileAPI);
        AppendToWorld(local, world, "ReadSharedLines", a.NewReadSharedLinesAPI);
        AppendToWorld(local, world, "WriteSharedFile", a.NewWriteSharedFileAPI);
        AppendToWorld(local, world, "SplitN", a.SplitNfunc);
        AppendToWorld(local, world, "UTF8Len", a.UTF8Len);
        AppendToWorld(local, world, "UTF8Index", a.UTF8Index);
        AppendToWorld(local, world, "UTF8Sub", a.UTF8Sub);
        AppendToWorld(local, world, "ToUTF8", a.ToUTF8);
        AppendToWorld(local, world, "FromUTF8", a.FromUTF8);
        AppendToWorld(local, world, "Info", a.Info);
        AppendToWorld(local, world, "InfoClear", a.InfoClear);
        AppendToWorld(local, world, "GetAlphaOption", a.GetAlphaOption);
        AppendToWorld(local, world, "SetAlphaOption", a.SetAlphaOption);
        AppendToWorld(local, world, "GetLinesInBufferCount", a.GetLinesInBufferCount);
        AppendToWorld(local, world, "DeleteOutput", a.DeleteOutput);
        AppendToWorld(local, world, "DeleteLines", a.DeleteLines);
        AppendToWorld(local, world, "GetLineCount", a.GetLineCount);
        AppendToWorld(local, world, "GetRecentLines", a.GetRecentLines);
        AppendToWorld(local, world, "GetLineInfo", a.GetLineInfo);
        AppendToWorld(local, world, "BoldColour", a.BoldColour);
        AppendToWorld(local, world, "NormalColour", a.NormalColour);
        AppendToWorld(local, world, "GetStyleInfo", a.GetStyleInfo);
        AppendToWorld(local, world, "GetInfo", a.GetInfo);
        AppendToWorld(local, world, "GetTimerInfo", a.GetTimerInfo);
        AppendToWorld(local, world, "GetTriggerInfo", a.GetTriggerInfo);
        AppendToWorld(local, world, "GetAliasInfo", a.GetAliasInfo);
        AppendToWorld(local, world, "WriteLog", a.WriteLog);
        AppendToWorld(local, world, "CloseLog", a.CloseLog);
        AppendToWorld(local, world, "OpenLog", a.OpenLog);
        AppendToWorld(local, world, "FlushLog", a.FlushLog);
        AppendToWorld(local, world, "Broadcast", a.Broadcast);
        AppendToWorld(local, world, "Notify", a.Notify);
        AppendToWorld(local, world, "Request", a.Request);
        AppendToWorld(local, world, "GetGlobalOption", a.GetGlobalOption);
        AppendToWorld(local, world, "CheckPermissions", a.CheckPermissions);
        AppendToWorld(local, world, "RequestPermissions", a.RequestPermissions);
        AppendToWorld(local, world, "CheckTrustedDomains", a.CheckTrustedDomains);
        AppendToWorld(local, world, "RequestTrustDomains", a.RequestTrustDomains);
        AppendToWorld(local, world, "Encrypt", a.Encrypt);
        AppendToWorld(local, world, "Decrypt", a.Decrypt);
        AppendToWorld(local, world, "DumpOutput", a.DumpOutput);
        AppendToWorld(local, world, "ConcatOutput", a.ConcatOutput);
        AppendToWorld(local, world, "SliceOutput", a.SliceOutput);
        AppendToWorld(local, world, "OutputToText", a.OutputToText);
        AppendToWorld(local, world, "FormatOutput", a.FormatOutput);
        AppendToWorld(local, world, "PrintOutput", a.PrintOutput);
        AppendToWorld(local, world, "Simulate", a.Simulate);
        AppendToWorld(local, world, "SimulateOutput", a.SimulateOutput);
        AppendToWorld(local, world, "DumpTriggers", a.DumpTriggers);
        AppendToWorld(local, world, "RestoreTriggers", a.RestoreTriggers);
        AppendToWorld(local, world, "DumpTimers", a.DumpTimers);
        AppendToWorld(local, world, "RestoreTimers", a.RestoreTimers);
        AppendToWorld(local, world, "DumpAliases", a.DumpAliases);
        AppendToWorld(local, world, "RestoreAliases", a.RestoreAliases);
        AppendToWorld(local, world, "SetHUDSize", a.SetHUDSize);
        AppendToWorld(local, world, "GetHUDContent", a.GetHUDContent);
        AppendToWorld(local, world, "GetHUDSize", a.GetHUDSize);
        AppendToWorld(local, world, "UpdateHUD", a.UpdateHUD);
        AppendToWorld(local, world, "NewLine", a.NewLine);
        AppendToWorld(local, world, "NewWord", a.NewWord);
        AppendToWorld(local, world, "SetPriority", a.SetPriority);
        AppendToWorld(local, world, "GetPriority", a.GetPriority);
        AppendToWorld(local, world, "SetSummary", a.SetSummary);
        AppendToWorld(local, world, "GetSummary", a.GetSummary);
        AppendToWorld(local, world, "Save", a.Save);
        AppendToWorld(local, world, "Milliseconds", a.Milliseconds);
        AppendToWorld(local, world, "OmitOutput", a.OmitOutput);
        AppendToWorld(local, world, "PrintSystem", a.PrintSystem);
#pragma warning restore CS8974 // 将方法组转换为非委托类型
        local.AddHostObject("world", world);
    }
}